/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_ucla_nesl_sigma_base_SigmaJNI */

#ifndef _Included_edu_ucla_nesl_sigma_base_SigmaJNI
#define _Included_edu_ucla_nesl_sigma_base_SigmaJNI
#ifdef __cplusplus
extern "C" {
#endif
#undef edu_ucla_nesl_sigma_base_SigmaJNI_MODE_PRIVATE
#define edu_ucla_nesl_sigma_base_SigmaJNI_MODE_PRIVATE 0L
#undef edu_ucla_nesl_sigma_base_SigmaJNI_MODE_WORLD_READABLE
#define edu_ucla_nesl_sigma_base_SigmaJNI_MODE_WORLD_READABLE 1L
#undef edu_ucla_nesl_sigma_base_SigmaJNI_MODE_WORLD_WRITEABLE
#define edu_ucla_nesl_sigma_base_SigmaJNI_MODE_WORLD_WRITEABLE 2L
#undef edu_ucla_nesl_sigma_base_SigmaJNI_MODE_APPEND
#define edu_ucla_nesl_sigma_base_SigmaJNI_MODE_APPEND 32768L
#undef edu_ucla_nesl_sigma_base_SigmaJNI_MODE_MULTI_PROCESS
#define edu_ucla_nesl_sigma_base_SigmaJNI_MODE_MULTI_PROCESS 4L
#undef edu_ucla_nesl_sigma_base_SigmaJNI_MODE_ENABLE_WRITE_AHEAD_LOGGING
#define edu_ucla_nesl_sigma_base_SigmaJNI_MODE_ENABLE_WRITE_AHEAD_LOGGING 8L
#undef edu_ucla_nesl_sigma_base_SigmaJNI_BIND_AUTO_CREATE
#define edu_ucla_nesl_sigma_base_SigmaJNI_BIND_AUTO_CREATE 1L
#undef edu_ucla_nesl_sigma_base_SigmaJNI_BIND_DEBUG_UNBIND
#define edu_ucla_nesl_sigma_base_SigmaJNI_BIND_DEBUG_UNBIND 2L
#undef edu_ucla_nesl_sigma_base_SigmaJNI_BIND_NOT_FOREGROUND
#define edu_ucla_nesl_sigma_base_SigmaJNI_BIND_NOT_FOREGROUND 4L
#undef edu_ucla_nesl_sigma_base_SigmaJNI_BIND_ABOVE_CLIENT
#define edu_ucla_nesl_sigma_base_SigmaJNI_BIND_ABOVE_CLIENT 8L
#undef edu_ucla_nesl_sigma_base_SigmaJNI_BIND_ALLOW_OOM_MANAGEMENT
#define edu_ucla_nesl_sigma_base_SigmaJNI_BIND_ALLOW_OOM_MANAGEMENT 16L
#undef edu_ucla_nesl_sigma_base_SigmaJNI_BIND_WAIVE_PRIORITY
#define edu_ucla_nesl_sigma_base_SigmaJNI_BIND_WAIVE_PRIORITY 32L
#undef edu_ucla_nesl_sigma_base_SigmaJNI_BIND_IMPORTANT
#define edu_ucla_nesl_sigma_base_SigmaJNI_BIND_IMPORTANT 64L
#undef edu_ucla_nesl_sigma_base_SigmaJNI_BIND_ADJUST_WITH_ACTIVITY
#define edu_ucla_nesl_sigma_base_SigmaJNI_BIND_ADJUST_WITH_ACTIVITY 128L
#undef edu_ucla_nesl_sigma_base_SigmaJNI_CONTEXT_INCLUDE_CODE
#define edu_ucla_nesl_sigma_base_SigmaJNI_CONTEXT_INCLUDE_CODE 1L
#undef edu_ucla_nesl_sigma_base_SigmaJNI_CONTEXT_IGNORE_SECURITY
#define edu_ucla_nesl_sigma_base_SigmaJNI_CONTEXT_IGNORE_SECURITY 2L
#undef edu_ucla_nesl_sigma_base_SigmaJNI_CONTEXT_RESTRICTED
#define edu_ucla_nesl_sigma_base_SigmaJNI_CONTEXT_RESTRICTED 4L
#undef edu_ucla_nesl_sigma_base_SigmaJNI_RESULT_CANCELED
#define edu_ucla_nesl_sigma_base_SigmaJNI_RESULT_CANCELED 0L
#undef edu_ucla_nesl_sigma_base_SigmaJNI_RESULT_OK
#define edu_ucla_nesl_sigma_base_SigmaJNI_RESULT_OK -1L
#undef edu_ucla_nesl_sigma_base_SigmaJNI_RESULT_FIRST_USER
#define edu_ucla_nesl_sigma_base_SigmaJNI_RESULT_FIRST_USER 1L
#undef edu_ucla_nesl_sigma_base_SigmaJNI_DEFAULT_KEYS_DISABLE
#define edu_ucla_nesl_sigma_base_SigmaJNI_DEFAULT_KEYS_DISABLE 0L
#undef edu_ucla_nesl_sigma_base_SigmaJNI_DEFAULT_KEYS_DIALER
#define edu_ucla_nesl_sigma_base_SigmaJNI_DEFAULT_KEYS_DIALER 1L
#undef edu_ucla_nesl_sigma_base_SigmaJNI_DEFAULT_KEYS_SHORTCUT
#define edu_ucla_nesl_sigma_base_SigmaJNI_DEFAULT_KEYS_SHORTCUT 2L
#undef edu_ucla_nesl_sigma_base_SigmaJNI_DEFAULT_KEYS_SEARCH_LOCAL
#define edu_ucla_nesl_sigma_base_SigmaJNI_DEFAULT_KEYS_SEARCH_LOCAL 3L
#undef edu_ucla_nesl_sigma_base_SigmaJNI_DEFAULT_KEYS_SEARCH_GLOBAL
#define edu_ucla_nesl_sigma_base_SigmaJNI_DEFAULT_KEYS_SEARCH_GLOBAL 4L
/*
 * Class:     edu_ucla_nesl_sigma_base_SigmaJNI
 * Method:    getMessage
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_ucla_nesl_sigma_base_SigmaJNI_getMessage
  (JNIEnv *, jclass);

/*
 * Class:     edu_ucla_nesl_sigma_base_SigmaJNI
 * Method:    socketpair
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_edu_ucla_nesl_sigma_base_SigmaJNI_socketpair
  (JNIEnv *, jclass);

/*
 * Class:     edu_ucla_nesl_sigma_base_SigmaJNI
 * Method:    closeFd
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_edu_ucla_nesl_sigma_base_SigmaJNI_closeFd
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_ucla_nesl_sigma_base_SigmaJNI
 * Method:    recvMessage
 * Signature: (ILjava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_edu_ucla_nesl_sigma_base_SigmaJNI_recvMessage
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     edu_ucla_nesl_sigma_base_SigmaJNI
 * Method:    sendMessage
 * Signature: (ILjava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_edu_ucla_nesl_sigma_base_SigmaJNI_sendMessage
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     edu_ucla_nesl_sigma_base_SigmaJNI
 * Method:    waitForMessage
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_edu_ucla_nesl_sigma_base_SigmaJNI_waitForMessage
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
