/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_ucla_nesl_sigma_base_SigmaJNI */

#ifndef _Included_edu_ucla_nesl_sigma_base_SigmaJNI
#define _Included_edu_ucla_nesl_sigma_base_SigmaJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_ucla_nesl_sigma_base_SigmaJNI
 * Method:    getMessage
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_ucla_nesl_sigma_base_SigmaJNI_getMessage
  (JNIEnv *, jclass);

/*
 * Class:     edu_ucla_nesl_sigma_base_SigmaJNI
 * Method:    socketpair
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_edu_ucla_nesl_sigma_base_SigmaJNI_socketpair
  (JNIEnv *, jclass);

/*
 * Class:     edu_ucla_nesl_sigma_base_SigmaJNI
 * Method:    closeFd
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_edu_ucla_nesl_sigma_base_SigmaJNI_closeFd
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_ucla_nesl_sigma_base_SigmaJNI
 * Method:    recvMessage
 * Signature: (ILjava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_edu_ucla_nesl_sigma_base_SigmaJNI_recvMessage
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     edu_ucla_nesl_sigma_base_SigmaJNI
 * Method:    sendMessage
 * Signature: (ILjava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_edu_ucla_nesl_sigma_base_SigmaJNI_sendMessage
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     edu_ucla_nesl_sigma_base_SigmaJNI
 * Method:    waitForMessage
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_edu_ucla_nesl_sigma_base_SigmaJNI_waitForMessage
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
