// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: sigma/proto/P.proto
package edu.ucla.nesl.sigma.P;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.STRING;

public final class SIntent extends Message {

  public static final String DEFAULT_ACTION = "";

  @ProtoField(tag = 1, type = STRING)
  public final String action;

  private SIntent(Builder builder) {
    super(builder);
    this.action = builder.action;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) {
      return true;
    }
    if (!(other instanceof SIntent)) {
      return false;
    }
    return equals(action, ((SIntent) other).action);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = action != null ? action.hashCode() : 0);
  }

  public static final class Builder extends Message.Builder<SIntent> {

    public String action;

    public Builder() {
    }

    public Builder(SIntent message) {
      super(message);
      if (message == null) {
        return;
      }
      this.action = message.action;
    }

    public Builder action(String action) {
      this.action = action;
      return this;
    }

    @Override
    public SIntent build() {
      return new SIntent(this);
    }
  }
}
