// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: proto/P.proto
package edu.ucla.nesl.sigma.P;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Label.REQUIRED;

public final class SSocketDataReceived extends Message {

    public static final String DEFAULT_BYTES = "";

    @ProtoField(tag = 1, type = STRING, label = REQUIRED)
    public final String bytes;

    private SSocketDataReceived(Builder builder) {
        super(builder);
        this.bytes = builder.bytes;
    }

    @Override
    public boolean equals(Object other) {
        if (other == this) return true;
        if (!(other instanceof SSocketDataReceived)) return false;
        return equals(bytes, ((SSocketDataReceived) other).bytes);
    }

    @Override
    public int hashCode() {
        int result = hashCode;
        return result != 0 ? result : (hashCode = bytes != null ? bytes.hashCode() : 0);
    }

    public static final class Builder extends Message.Builder<SSocketDataReceived> {

        public String bytes;

        public Builder() {
        }

        public Builder(SSocketDataReceived message) {
            super(message);
            if (message == null) return;
            this.bytes = message.bytes;
        }

        public Builder bytes(String bytes) {
            this.bytes = bytes;
            return this;
        }

        @Override
        public SSocketDataReceived build() {
            checkRequiredFields();
            return new SSocketDataReceived(this);
        }
    }
}
