// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: sigma/proto/P.proto
package edu.ucla.nesl.sigma.P;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.BOOL;
import static com.squareup.wire.Message.Label.REQUIRED;

public final class STransactionResponse extends Message {

  public static final Boolean DEFAULT_RETURN = false;

  @ProtoField(tag = 1, label = REQUIRED)
  public final SParcel reply;

  @ProtoField(tag = 2, type = BOOL, label = REQUIRED)
  public final Boolean _return;

  private STransactionResponse(Builder builder) {
    super(builder);
    this.reply = builder.reply;
    this._return = builder._return;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) {
      return true;
    }
    if (!(other instanceof STransactionResponse)) {
      return false;
    }
    STransactionResponse o = (STransactionResponse) other;
    return equals(reply, o.reply)
           && equals(_return, o._return);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = reply != null ? reply.hashCode() : 0;
      result = result * 37 + (_return != null ? _return.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<STransactionResponse> {

    public SParcel reply;
    public Boolean _return;

    public Builder() {
    }

    public Builder(STransactionResponse message) {
      super(message);
      if (message == null) {
        return;
      }
      this.reply = message.reply;
      this._return = message._return;
    }

    public Builder reply(SParcel reply) {
      this.reply = reply;
      return this;
    }

    public Builder _return(Boolean _return) {
      this._return = _return;
      return this;
    }

    @Override
    public STransactionResponse build() {
      checkRequiredFields();
      return new STransactionResponse(this);
    }
  }
}
